version: '2'

services:
  admin:
    depends_on:
      - api
    build: admin
    ports:
      - "80"
    environment:
      PORT: "80"
    volumes:
      - ./admin:/usr/src/app/
    labels:
      - "traefik.backend=admin"
      - "traefik.frontend.rule=PathPrefix: /"
  api:
    depends_on:
      - db
    build: api
    ports:
      - "8080"
    environment:
      MONGODB_URI: mongodb://db:27017
    volumes:
      - ./api:/usr/src/app/
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix: /api"
  proxy:
    restart: always
    image: traefik
    command: --web --docker --docker.domain=docker.localhost
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - "27017"

volumes:
  db_data:
