version: '2'

services:
  api:
    depends_on:
      - db
    build: api
    ports:
      - "3333:8080"
    environment:
      MONGODB_URI: mongodb://db:27017
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - "27017:27017"

volumes:
  db_data:
