version: '2'

services:
  admin:
    depends_on:
      - api
    build: admin
    ports:
      - "80:80"
    environment:
      PORT: "80"
    volumes:
      - ./admin:/usr/src/app/
  api:
    depends_on:
      - db
    build: api
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    environment:
      MONGODB_URI: mongodb://db:27017
    volumes:
      - ./api:/usr/src/app/
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - "27017"

volumes:
  db_data:
