version: '2'

services:
  web:
    depends_on:
      - api
    build: web
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
    volumes:
      - ./web:/usr/src/app/
  admin:
    depends_on:
      - api
    build: admin
    ports:
      - "80:80"
    environment:
      PORT: "80"
    volumes:
      - ./admin:/usr/src/app/
  api:
    depends_on:
      - db
    build: api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: "8080"
    volumes:
      - ./api:/usr/src/app/
  db:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - "27017"

volumes:
  db_data:
